spring:
  jpa:
    show-sql: true
    properties:
      hibernate.jdbc.batch_size: 1000
      hibernate.order_inserts: true
      hibernate.order_updates: true
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:13306/batch-insert
      username: root
      password: root
      driver-class-name: org.mariadb.jdbc.Driver
      data-source-properties:
        rewriteBatchedStatements: true
