spring:
  jpa:
#    show-sql: true
    properties:
      hibernate:
        jdbc.batch_size: 1000
        order_inserts: true
        order_updates: true
#      hibernate.id.new_generator_mappings: false
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:13306/batch-insert?profileSQL=true
      username: root
      password: root
      driver-class-name: org.mariadb.jdbc.Driver
      data-source-properties:
        rewriteBatchedStatements: true
#        rewriteBatchedStatements: true 는 우선순위를 가장 높게 가지는 jdbc-url에 적어주도록 하자.
